services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 9003:80
      # - 9103:3000 # Apenas pra config inicial
    volumes:
      - ./data/adguardhome/config:/opt/adguardhome/conf
      - ./data/adguardhome/work:/opt/adguardhome/work
    networks:
      dns_network:
          ipv4_address: 172.28.0.11

    restart: unless-stopped
    depends_on:
      - adguardhome-unbound

  adguardhome-unbound:
    image: mvance/unbound:latest
    container_name: adguardhome-unbound
    volumes:
      - ./data/unbound:/opt/unbound/etc/unbound/
    restart: unless-stopped
    networks:
      dns_network:
        ipv4_address: 172.28.0.10 # usar esse ip no AdGuard
    healthcheck:
      test: ["NONE"]

networks:
  dns_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
