services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      # - 9103:3000 # Apenas pra config inicial
    volumes:
      - ./data/adguardhome/config:/opt/adguardhome/conf
      - ./data/adguardhome/work:/opt/adguardhome/work
    networks:
      swag-net:
      dns-net:
          ipv4_address: 172.28.0.11

    restart: unless-stopped
    depends_on:
      - adguardhome-unbound
    healthcheck:
      test: nslookup www.google.com localhost || exit 1
      timeout: 5s
      interval: 30s
      start_period: 10s
      retries: 3

  adguardhome-unbound:
    image: mvance/unbound:latest
    container_name: adguardhome-unbound
    volumes:
      - ./data/unbound:/opt/unbound/etc/unbound/
    restart: unless-stopped
    networks:
      dns-net:
        ipv4_address: 172.28.0.10 # usar esse ip no AdGuard
    healthcheck:
      test: drill @localhost www.google.com || exit 1
      timeout: 5s
      interval: 30s
      start_period: 10s
      retries: 3

networks:
  swag-net:
    external: true
  dns-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
