services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    environment:
      - TZ=${TZ}
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/data:/data
    restart: unless-stopped
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
