services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
      - WEBUI_PORT=9001
    volumes:
      - ./data/qbittorrent/config:/config
      - /mnt/hdd/data/torrents:/downloads
    ports:
      - "9001:9001"
    depends_on:
      - qbittorrent-jackett
    networks:
      - qbittorrent_network

  qbittorrent-jackett:
    image: lscr.io/linuxserver/jackett
    container_name: qbittorrent-jackett
    environment:
      - PUID=1000
      - PGID=1000
      - AUTO_UPDATE=true
    volumes:
      - ./data/jackett/config:/config
    restart: unless-stopped
    ports:
      - "9101:9117"
    networks:
      - qbittorrent_network

networks:
  qbittorrent_network:
    driver: bridge
