services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=9001
    volumes:
      - ./data/qbittorrent/config:/config
      - /mnt/hdd/public/data/torrents:/downloads
    networks:
      - swag-net
    healthcheck:
      test: curl --fail --silent --show-error --max-time 5 http://localhost:9001 || exit 1
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3

# Realmente vale a pena? acho q n vale o tempo de manutenção
  # qbittorrent-jackett:
  #   image: lscr.io/linuxserver/jackett
  #   container_name: qbittorrent-jackett
  #   environment:
  #     - AUTO_UPDATE=true
  #   volumes:
  #     - ./data/jackett/config:/config
  #   restart: unless-stopped
  #   ports:
  #     - "9101:9101"

networks:
  swag-net:
    external: true
