services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${PUID}:${PGID}
    networks:
      - swag-net
    volumes:
      - ./data/config:/config
      - ./data/cache:/cache
      - /mnt/hdd/jellyfin:/media:ro
      - /mnt/hdd/:/mnt/hdd/ # Precisa mapear o hd pros links simbólicos funcionarem
    restart: 'unless-stopped'

networks:
  swag-net:
    external: true
