services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${PUID}:${PGID}
    ports:
      - 9004:8096
    volumes:
      - ./data/config:/config
      - ./data/cache:/cache
      - /mnt/hdd/jellyfin:/media:ro
      - /mnt/hdd/:/mnt/hdd/ # Precisa mapear o hd pros links simbolicos funcionarem
    restart: 'unless-stopped'
