services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - swag-net
    restart: unless-stopped
    volumes:
      - ./data/config:/app/config
      - ./data/icons:/app/public/icons
      - ./data/images:/app/public/images
      - /mnt/hdd:/mnt/hdd
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
      - TZ=${TZ}

networks:
  swag-net:
    external: true