services:
  nime-fetch:
    image: gregoryesberci/nime-fetch:latest
    container_name: nime-fetch
    restart: "no"
    user: "${PUID:-1000}:${PGID:-1000}"
    networks:
      - swag-net
    volumes:
      - /mnt/hdd/public/data/mine-fetch:/downloads
      - ./data/database:/database
    environment:
      BASE_PATH: /nime-fetch

networks:
  swag-net:
    external: true
