services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    environment:
      UID: ${PUID}
      GUI: ${PGID}
      DOWNLOAD_DIR: /downloads/videos
      AUDIO_DOWNLOAD_DIR: /downloads/audios
      URL_PREFIX: /metube
    networks:
      - swag-net
    volumes:
      - /mnt/hdd/public/data/youtube:/downloads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3

networks:
  swag-net:
    external: true
