services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - /mnt/hdd/data:/srv
      - ./data/filebrowser.db:/filebrowser.db
      - ./data/filebrowser.json:/.filebrowser.json
    ports:
      - "9002:80"
    user: "${PUID}:${PGID}"
